export const FETCH_PRODUCT = "FETCH_PRODUCT"
export const SET_PRODUCTS = "SET_PRODUCTS"
export const SET_HANDLEINPUTPRODUCTS = "SET_HANDLEINPUTPRODUCTS"
export const SET_HANDLEINPUT_PRODUCTS = "SET_HANDLEINPUT_PRODUCTS"
export const INSERT_NEW_PRODUCT = "INSERT_NEW_PRODUCT"
export const SET_BARCODE_SCANNER = "SET_BARCODE_SCANNER"
export const UPDATE_BASKET_CHECKED = "UPDATE_BASKET_CHECKED"
export const SET_UPDATE_BASKET_CHECKED = "SET_UPDATE_BASKET_CHECKED"
export const DELETE_BASKET_CHECKED = "DELETE_BASKET_CHECKED"
export const SET_DELETE_BASKET_CHECKED= "SET_DELETE_BASKET_CHECKED"
export const DELETE_PRODUCT = "DELETE_PRODUCT"
export const CLEAR_BASKET_CHECKED = "CLEAR_BASKET_CHECKED"
export const SET_CLEAR_BASKET_CHECKED= "SET_CLEAR_BASKET_CHECKED"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
export const SET_SEARCH_PRODUCT = "SET_SEARCH_PRODUCT"
export const SORT_PRODUCT = "SORT_PRODUCT"
export const SET_UPDATE_CASHIER = "SET_UPDATE_CASHIER"
export const ADD_BASKET_CASHIER = "ADD_BASKET_CASHIER"

export const dispatchProducts = (type,obj) => ({
    type: type,payload:obj.value,key:obj.key
});