export const SET_HANDLEINPUTUNIT = "SET_HANDLEINPUTUNIT"
export const SET_HANDLEINPUT_UNIT = "SET_HANDLEINPUT_UNIT"
export const FETCH_UNITS = "FETCH_UNITS"
export const SET_UNITS = "SET_UNITS"
export const INSERT_NEW_UNIT = "INSERT_NEW_UNIT"
export const UPDATE_BASKET_CHECKED_UNITS = "UPDATE_BASKET_CHECKED_UNITS"
export const DELETE_BASKET_CHECKED_UNITS = "DELETE_BASKET_CHECKED_UNITS"
export const SET_UPDATE_BASKET_CHECKED_UNITS = "SET_UPDATE_BASKET_CHECKED_UNITS"
export const SET_DELETE_BASKET_CHECKED_UNITS = "SET_DELETE_BASKET_CHECKED_UNITS"
export const SET_CLEAR_BASKET_CHECKED_UNITS = "SET_CLEAR_BASKET_CHECKED_UNITS"

export const dispatchUnits = (type,obj) => ({
    type: type,payload:obj.value,key:obj.key
});